data:
  data_location: ./data
  extension: wav

preprocess:
  sampling_rate: &samplingrate 48000
  signal_length: &signallength 192000 # error when signal_length / block_size is not an integer
  block_size: &blocksize 512 # must be a power of 2 if using realtime # error when > real-time buffer size
  oneshot: false # crop every audio file to exactly signal length
  out_dir: ./preprocess

mfcc:
  fft_sizes: 1024
  mel_bins: 128
  mfcc_bins: 30

model:
  hidden_size: 512
  n_harmonic: 100
  n_bands: 65
  sampling_rate: *samplingrate
  block_size: *blocksize

train:
  model_name: name
  scales: [4096, 2048, 1024, 512, 256, 128]
  overlap: 0.75
  steps: 30000
  eval_steps: 100
  batch_size: 16
  learning_rate_start: 0.001
  learning_rate_stop: 0.0001
  decay: 24000
  out_dir: ./train

export:
  out_dir: ./export
  realtime: true