data:
  data_location: ./data
  extension: wav

preprocess:
  sampling_rate: &samplingrate 48000
  signal_length: &signallength 192000  # signal_length / block_size must be an integer
  block_size: &blocksize 512  # must be a power of 2 if using realtime # error when > real-time buffer size
  oneshot: false  # crop every audio file to exactly signal length
  out_dir: ./preprocess

model:
  architecture: audio_decoder  # choose between 'audio_decoder', 'control_decoder' and 'latent_decoder'
  hidden_size: 512
  n_harmonic: 100
  n_bands: 65
  sampling_rate: *samplingrate
  block_size: *blocksize

mfcc:  # for latent-decoder
  fft_sizes: 1024  # default 1024
  mel_bins: 64  # default 128
  mfcc_bins: 3  # default 30

train:
  model_name: name
  scales: [4096, 2048, 1024, 512, 256, 128]
  overlap: 0.75
  steps: 30000
  eval_steps: 100
  batch_size: 16
  learning_rate_start: 0.001
  learning_rate_stop: 0.0001
  decay: 24000
  out_dir: ./train

export:
  out_dir: ./export